name: Release iOS XCFramework

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get this Tag version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Assemble
        run: ./gradlew :example:assemble

      - name: Make it Fat
        run: |
          xcodebuild -create-xcframework -framework example/build/bin/iosArm64/debugFramework/example.framework -framework example/build/bin/iosX64/debugFramework/example.framework -output example/build/bin/KotlinNativeExample.xcframework

      - name: Upload Fat XCFramework to Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Fat-Framework
          path: example/build/bin/KotlinNativeExample.xcframework

      - name: Checkout Frameworks Repo
        uses: actions/checkout@v2
        with:
          repository: vitorhugods/KotlinNativeMobileFrameworks
          token: ${{ secrets.GIT_PAT }}
          path: frameworks-repo

      - name: Upload current build
        run: |
          cp .github/workflows/resources/shared.podspec frameworks-repo/
          cp -R example/build/bin/KotlinNativeExample.xcframework frameworks-repo/
          cd frameworks-repo
          git add .
          git commit -m "Built from TAG: ${{ steps.get_version.outputs.VERSION }}"
          git tag -a ${{ steps.get_version.outputs.VERSION }} -m "Built from TAG: ${{ steps.get_version.outputs.VERSION }}"
          git push origin --tags