name: Write in another repo

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Checkout Frameworks Repo
        uses: actions/checkout@v2
        with:
          repository: vitorhugods/KotlinNativeMobileFrameworks
          token: ${{ secrets.GIT_PAT }}
          path: frameworks-repo

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Attempt to change destination
        run: |
          cd frameworks-repo
          touch file.txt
          git add .
          git commit -m "This is a test, ${{ steps.get_version.outputs.VERSION }}"
          git push